blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = false
hex_literal_case = "Lower"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 100
merge_derives = false
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
struct_lit_single_line = false
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
